version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build_script:
  - ps: ./scripts/build.ps1
environment:
  APPVEYOR_REPO_TAG: true
artifacts:
  - path: FlaivySharp/bin/Release/netcoreapp2.2
    name: netcoreapp22
  - path: FlaivySharp/bin/Release/net461
    name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
  - provider: NuGet
    api_key:
      secure: m4LmaNm+G0T/GpZNmbtXztcqPT70tMQJ8xrGFhWz6tp4j8wT6yAH3nSzuKkIsVBN
    on:
      branch: master
